// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {marketdata} from '../models';

export function GetCandles(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<marketdata.Candle>>;

export function GetSymbols(arg1:string,arg2:string,arg3:string):Promise<Array<marketdata.Symbol>>;

export function StartMarketStream(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StopMarketStream():Promise<void>;
